apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: celosop/drupal8
          ports:
          - containerPort: 80
            name: http
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: drupal
  type: NodePort