apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: celosop/drupal8
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          volumeMounts:
            - name: nfs-volume
              mountPath: /var/www/html
      volumes:
        - name: nfs-volume
          nfs:
            server: 172.16.64.238
            path: /mnt/hd1

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: drupal
  type: NodePort