apiVersion: v1
kind: Service
metadata:
  name: db-ojs
spec:
  ports:
  - port: 3306
  selector:
    app: db-ojs
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ojsdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manualojs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/hd2/ojs
    server: 172.16.64.238

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ojsdb-pv-claim
spec:
  storageClassName: manualojs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: ojs-service
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31234
  selector:
    app: ojs
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-ojs
  name: db-ojs
spec:
  selector:
    matchLabels:
      app: db-ojs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-ojs
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: ojs
        - name: MYSQL_PASSWORD
          value: ojsPwd
        - name: MYSQL_ROOT_PASSWORD
          value: ojsPwd
        - name: MYSQL_USER
          value: ojs
        image: mariadb:10.2
        name: ojs-db
        volumeMounts:
        - name: ojsdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: ojsdb-persistent-storage
        persistentVolumeClaim:
          claimName: ojsdb-pv-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojs
  labels:
    app: ojs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ojs
  template:
    metadata:
      labels:
        app: ojs
    spec:
      initContainers:
      - name: init-ojs
        image: celosop/ojsufrpe:3
        command: ['sh', '-c', "cp -rP /var/www/html/* /tmp/"]
        volumeMounts:
          - name: ojsvolume
            mountPath: /tmp/
      containers:
      - name: ojs
        image: celosop/ojsufrpe:3
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
          - name: ojsvolume
            mountPath: /var/www/html/
      volumes:
        - name: ojsvolume
          nfs:
            server: 172.16.64.238
            path: /mnt/hd2/ojs