apiVersion: v1
kind: Service
metadata:
  name: ojs-service
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31234
  selector:
    app: ojs
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
    app: db-ojs
  name: db-ojs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-ojs
  template:
    metadata:
      labels:
        app: db-ojs
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: ojs
        - name: MYSQL_PASSWORD
          value: ojsPwd
        - name: MYSQL_ROOT_PASSWORD
          value: ojsPwd
        - name: MYSQL_USER
          value: ojs
        image: mariadb:10.2
        name: ojs-db
      volumes: null

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojs
  labels:
    app: ojs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ojs
  template:
    metadata:
      labels:
        app: ojs
    spec:
      containers:
        - name: ojs
          image: celosop/ojsufrpe:3
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
