apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.8
          ports:
          - containerPort: 80
          volumeMounts:
            - name: nfs-volume
              mountPath: /usr/share/nginx/html/ # Please change the destination you like the share to be mounted too
      volumes:
        - name: nfs-volume
          nfs:
            server: 172.16.64.238 # Please change this to your NFS server
            path: /mnt/hd1 # Please change this to the relevant share