apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojs
  labels:
    app: ojs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ojs
  template:
    metadata:
      labels:
        app: ojs
    spec:
      containers:
        - name: ojs
          image: pkpofficial/ojs:3_2_1-1
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ojs-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: ojs
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: ojsPwd
        - name: MYSQL_DATABASE
          value: ojs
        - name: MYSQL_USER
          value: ojs
        - name: MYSQL_PASSWORD
          value: ojsPwd
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/hd1
    server: 172.16.64.238
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi